### ISSUE TITLE
Miami's own Ohana Web Search app

### ISSUE THREAD

**Issue by eddroid** [Code-for-Miami/ohana-api#13]
Ohana comes in two parts: [API](https://github.com/codeforamerica/ohana-api) and [search](https://github.com/codeforamerica/ohana-web-search). These are two separate apps running at two separate URLs with two separate GitHub repos.

This GitHub repo represents Miami's Ohana API app. "API" is partly a misnomer. Yes, there are [computer-friendly JSON data endpoints](https://miami-open-211.herokuapp.com/api/) available, along with [a Ruby Gem for making API calls easier](https://github.com/codeforamerica/ohanakapa-ruby), but there's also [a user signup/login feature](https://miami-open-211.herokuapp.com/) that human volunteers can use to add and update the underlying API data.

Miami does not yet have a working fork of the Ohana Web Search app. The search app is a primarily human-facing app that allows people to search for services. 

The Web Search app is actually an Ohana API client. It pulls it's data from the API. So there remains a single, canonical data source.

The Web Search app also links back to the API if a user expresses an interest in adding to or updating the underlying data.

This project needs a working, customized version of the Ohana Web Search app.
1. Fork the [search app](https://github.com/codeforamerica/ohana-web-search).
2. Configure the fork's [OHANA_API_ENDPOINT](https://github.com/codeforamerica/ohana-web-search/blob/master/config/application.example.yml) to point to [Miami's API endpoint](https://miami-open-211.herokuapp.com/api/).
3. [Deploy Miami's Ohana Search App to Heroku](https://github.com/codeforamerica/ohana-web-search/wiki/How-to-deploy-Ohana-Web-Search-to-your-Heroku-account).
4. Misc debugging, configuration, and customization.

When you're done, the @Code-for-Miami/owners will:
- [ ] Fork your repo into this account and add you as a collaborator.
- [ ] Ask you to transfer ownership of the Heroku app to CodeForMiami's Heroku account.
- [ ] Add you as a collaborator to (what is now) CodeForMiami's Heroku app.

Afterwards, you and any other collaborators can continue to push and deploy changes to GitHub and Heroku.

**Comment by greggish** [comment]
@eddroid this looks great. I'm in Wynwood, gonna come swing by the Lab in
about an hour or so - hope to catch ya.

**Comment by eddroid** [comment]
@greggish https://github.com/Code-for-Miami/ohana-web-search and https://ed-miami-ohana-web-search.herokuapp.com/. That's not the official CfM URL. The site still needs debugging. But we can create issues in the other repo for that.
