### ISSUE TITLE
make the human-friendly API human-friendly

### ISSUE THREAD

**Issue by bkerley** [Code-for-Miami/ohana-api#3]
from @eddroid in slack:

> implementing and styling the human friendly (web) version of the API

**Comment by bkerley** [comment]
Okay, so chatting with @cyberstrike : the big thing is making a UI, which probably means starting with HTML views for existing API URLs.

**Comment by eddroid** [comment]
https://github.com/codeforamerica/ohana-web-search

**Comment by bkerley** [comment]
The tack we're taking today is making the API more developer-friendly with views for most JSON endpoints that display and describe the data in a more semantically useful way than face-full-of-JSON.

**Comment by eddroid** [comment]
Sounds like we're confusing the human-friendly web-search with a human-friendly API browser. Should those be separate issues?

I don't understand why the web search isn't part of the sample API app already. It should be the same data.

**Comment by eddroid** [comment]
p.s. [These are the Ohana API docs](http://codeforamerica.github.io/ohana-api-docs/) if you're interested in making something more API developer friendly.

**Comment by eddroid** [comment]
Let's do https://github.com/Code-for-Miami/ohana-api/issues/13 instead.
